### ISSUE TITLE
Lacking instructions and probably dysfunctional?

### ISSUE THREAD

**Issue by smileBeda** [sublimelsp/LSP-SonarLint#10]
- The readme does not have complete installation nor usage nor setup instructions
- The actual feature is probably broken.

For example after this https://github.com/sublimelsp/LSP-SonarLint/issues/8 I tried saving the release into the `Sublime Text 3 > Packages` folder which _seems_ to have resolve that error.
Why do I even need to do this? Why is it not documented?

Then, it still does not lint a thing. It just says "Sonarlint line 1" for example when saving a file with a few lines of PHP.
I can't figure out how I would connect this to my SonarCloud instance so I could pull my own ruleset. 

Is this project maintained, and if so, is someone willing to instruct how to use it?

Thanks.

**Comment by smileBeda** [comment]
I am sorry to say, installed VSCode, in 2 minutes.
Installed its SonarCloud Integration, another 1.5 minutes.
Took me some time (another 3 minutes) to figure out where the errors actually would be shown.

Not only did I waste days on the ST integration, but, VSCode one actually uses my custom rule set. Out of the box. Just like that.

That's it, I am off ST. Subscription cancelled. This entire project, is doomed for decline, if nothing is done to integrate it with the current year of 2023

I literally _loved_ ST and was an eager defender and promoter of this tool, but the handling of this particular integration just shows that it's not worth the shot. Anymore. 

... in another 20 minutes WPCS was installed and another 5 minutes later the tool was complete.
It is unfamiliar, yes, after working for _years_ with ST, but I will get used to it. And lose less time.

This remembers me of a day several years ago when a senior dev called me masochist for using ST. 😢

**Comment by rchl** [comment]
Sorry to hear but this is a free project maintained by volunteers for free. Also it's not affiliated with ST and its developers. LSP support is not part of the core ST.

SonalLint in particular is not something that any of the volunteers was particularly interested in getting to work it seems. Neither its authors were interesting in supporting ST I guess. So I guess the issue stems from multiple directions and sources.

Since the VSCode extension is maintained by the company behind SonarLint, it makes sense that it all works and is easy to use.

**Comment by rchl** [comment]
If there would be some volunteer that would have enough interest in getting this project up and running then I guess it could be as good and easy to use as the vscode extension. But currently we don't seem to have anyone like that.

**Comment by smileBeda** [comment]
I do understand that, completely.
Unluckily, while I do understand python, I never even touched a ST extension code (I checked the Linter source code which was easy enough, but the LSP one is already another animal)

If I had the time to learn and develop this further, I would. But unfortunately - and as I am sure many others - I use(d) ST to _perform work for clients_ (and paid my share to ST because I loved it).
I have to say that it is always the same with os projects: they are cool, until the interest disappears. Then, the users are literally left up dry.

I love OS, I love the spirit and community, but not everyone who _has to make a living_ and already contributes to a ton of other projects, has the time to maintain the tools they use. Which is, by no surprise, probably a reason we see less and less of the OS tools around.

It is a "shame", but also a logical consequence. If a corporation like Microsoft throws a VScode out there, for free... I mean, yes, it's a corp and all that, but do I care? In the end I need to get a job done, not make more work.

Don't get me wrong, I know that this is the wrong place to discuss it, I know it is _hard_ to maintain an OS project, I know everyone always wants everything for free. This is not what I expect. I would be willing to pay 200 dollars yearly to ST - even more! But we cannot expect _every user_ of an OS project to also contribute to it :)
That is not how the world works. A few make, many use, some finance. That is just how it is - and it seems to me, that it somehow always gets offloaded as the "user's fault" to not contribute.

I think this is a broader problem of the OS world: the world _does not work like that_ - it needs actual people that _focus_ on the specific task. For example, I do PHP DEV.
I can contribute here, of course, but to what end? Learning ST alone takes longer than installing VSCode and using it. Not to mention contributing to its (still awesome and broad) community... 

This very example here, where a big tool like SonarCloud just plain out refuses to see one of the major Code Editors (ST) and ST folks somehow plain out ignore SonarCloud as one of the major linters... I don't know, but it speaks bands to me: the good stuff is where the lots of money is thrown at, it seems.

I am sponsoring PHPDoc for example, _just because I do not want it to die as well_
I pai(d) ST subscription _just because I thought it is THE tool_
But, it does not help. My world moves... and does not stand still. So I have to move, along with it

Sorry, really - again I want to clarify that I do not hold you or anyone else _responsible_ for this - if any, then the entire _society_ is responsible for these situations.
It's just that I (and many as me I believe) _have to_ move along what works best, in order to feed our mouths, in the end.

I hope this makes somehow sense
